/* ---------- Tabs ---------- */
document.querySelectorAll(".tab-btn").forEach(btn => {
  btn.addEventListener("click", () => {
    document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
    document.querySelectorAll(".tab-panel").forEach(p => p.classList.remove("active"));
    btn.classList.add("active");
    document.getElementById(btn.dataset.tab).classList.add("active");
    document.querySelector("main").classList.toggle("wide", document.getElementById(btn.dataset.tab).classList.contains("wide"));
  });
});

/* ---------- Cutoff data (data/cutoffs.js, generated by pipeline/normalize.py) ----------
   CUTOFFS.rows: [source_id, quota_idx, institute_idx, course_idx, category_idx, pwd, opening, closing, seats] */
const R = { SRC: 0, QUOTA: 1, INST: 2, COURSE: 3, CAT: 4, PWD: 5, OPEN: 6, CLOSE: 7, SEATS: 8 };
const SOURCES = Object.fromEntries(CUTOFFS.sources.map(s => [s.id, s]));
const YEARS = [...new Set(CUTOFFS.sources.map(s => s.year))].sort((a, b) => b - a);
const ROUND_ORDER = ["Round 1", "Round 2", "Round 3", "Mop-Up", "Stray Vacancy", "Special Stray"];
// Armed Forces seats are ranked by AFMS merit, not NEET rank, so they can't be predicted from a NEET rank.
const PREDICTABLE_QUOTAS = CUTOFFS.quotas.map((q, i) => [q, i]).filter(([q]) => q !== "Armed Forces");
const STATES = [...new Set(CUTOFFS.institutes.map(i => i[2]).filter(Boolean))].sort();
const PROGRAMS = [...new Set(CUTOFFS.courses.map(c => c[1]).filter(Boolean))];
const SPECIALTIES = [...new Set(CUTOFFS.courses.map(c => c[2]))].sort();

const esc = s => String(s ?? "").replace(/[&<>"]/g, ch => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch]));
const fmt = n => n == null ? "—" : n.toLocaleString("en-IN");
const instLabel = i => {
  const [name, city, state] = CUTOFFS.institutes[i];
  return `<strong>${esc(name)}</strong><br><span class="dim">${esc([city, state].filter(Boolean).join(", "))}</span>`;
};

function fillSelect(id, options, anyLabel) {
  const el = document.getElementById(id);
  el.innerHTML = (anyLabel ? `<option value="">${anyLabel}</option>` : "") +
    options.map(([value, label]) => `<option value="${esc(value)}">${esc(label)}</option>`).join("");
}

function courseMatches(courseIdx, program, specialty) {
  const c = CUTOFFS.courses[courseIdx];
  return (!program || c[1] === program) && (!specialty || c[2] === specialty);
}

/* ---------- Rank Predictor ---------- */
fillSelect("p-quota", [["aiq", "All India Quota (AIQ)"], ["all", "All MCC quotas"], ...PREDICTABLE_QUOTAS.map(([q, i]) => [i, q])]);
fillSelect("p-program", PROGRAMS.map(p => [p, p]), "All programs");
fillSelect("p-specialty", SPECIALTIES.map(s => [s, s]), "All specialties");
fillSelect("p-state", STATES.map(s => [s, s]), "All states");
fillSelect("p-year", YEARS.map(y => [y, y]));

{
  const n = CUTOFFS.rows.reduce((sum, r) => sum + r[R.SEATS], 0);
  document.getElementById("data-stats").textContent =
    `${n.toLocaleString("en-IN")} real allotments from ${CUTOFFS.sources.length} MCC result PDFs (${YEARS[YEARS.length - 1]}–${YEARS[0]})`;
}

document.getElementById("predictor-form").addEventListener("submit", e => {
  e.preventDefault();
  const rank = Number(document.getElementById("p-rank").value);
  const cat = Number(document.getElementById("p-category").value);
  const pwd = document.getElementById("p-pwd").value === "yes";
  const quotaSel = document.getElementById("p-quota").value;
  const program = document.getElementById("p-program").value;
  const specialty = document.getElementById("p-specialty").value;
  const state = document.getElementById("p-state").value;
  const year = Number(document.getElementById("p-year").value);

  const aiq = CUTOFFS.quotas.indexOf("All India");
  const quotaOk = q => quotaSel === "aiq" ? q === aiq
    : quotaSel === "all" ? PREDICTABLE_QUOTAS.some(([, i]) => i === q)
    : q === Number(quotaSel);
  const rounds = ROUND_ORDER.filter(r => CUTOFFS.sources.some(s => s.year === year && s.round === r));

  // seat key -> { round -> best (highest) closing rank among the seat categories this candidate can take }
  const seats = new Map();
  for (const r of CUTOFFS.rows) {
    const src = SOURCES[r[R.SRC]];
    if (src.year !== year) continue;
    if (r[R.CAT] !== 0 && r[R.CAT] !== cat) continue;       // Open seats + own category
    if (r[R.PWD] && !pwd) continue;                          // PwD seats only for PwD candidates
    if (!quotaOk(r[R.QUOTA])) continue;
    if (!courseMatches(r[R.COURSE], program, specialty)) continue;
    if (state && CUTOFFS.institutes[r[R.INST]][2] !== state) continue;
    const key = `${r[R.INST]}|${r[R.COURSE]}|${r[R.QUOTA]}`;
    let s = seats.get(key);
    if (!s) seats.set(key, s = { inst: r[R.INST], course: r[R.COURSE], quota: r[R.QUOTA], close: {} });
    s.close[src.round] = Math.max(s.close[src.round] || 0, r[R.CLOSE]);
  }

  const reachable = [];
  for (const s of seats.values()) {
    const within = rounds.filter(rd => s.close[rd] >= rank);
    if (!within.length) continue;
    s.firstRound = within[0];
    s.sortKey = Math.min(...within.map(rd => s.close[rd]));
    reachable.push(s);
  }
  // Tightest fit first: seats whose closing rank was just above yours are the most competitive ones in reach.
  reachable.sort((a, b) => a.sortKey - b.sortKey);
  renderPredictorResults(reachable, rank, year, rounds, seats.size);
});

let predictorShown = 100;
function renderPredictorResults(rows, rank, year, rounds, considered, keepCount) {
  if (!keepCount) predictorShown = 100;
  const container = document.getElementById("predictor-results");
  if (rows.length === 0) {
    container.innerHTML = `<div class="empty-state">In ${year}, none of the ${considered.toLocaleString("en-IN")} matching seats
      went to anyone ranked ${fmt(rank)} or worse, in any round. Try another year, quota, program or state.</div>`;
    return;
  }
  const byRound = {};
  rows.forEach(s => byRound[s.firstRound] = (byRound[s.firstRound] || 0) + 1);
  const summary = rounds.filter(r => byRound[r]).map(r => `${byRound[r].toLocaleString("en-IN")} first reachable in ${r}`).join(" · ");
  const body = rows.slice(0, predictorShown).map(s => `
    <tr>
      <td>${instLabel(s.inst)}</td>
      <td>${esc(CUTOFFS.courses[s.course][0])}</td>
      <td>${esc(CUTOFFS.quotas[s.quota])}</td>
      ${rounds.map(rd => `<td class="num ${s.close[rd] >= rank ? "ok" : s.close[rd] ? "miss" : ""}">${fmt(s.close[rd])}</td>`).join("")}
    </tr>`).join("");
  container.innerHTML = `
    <p class="result-summary"><strong>${rows.length.toLocaleString("en-IN")}</strong> of ${considered.toLocaleString("en-IN")}
      matching seats were allotted at or beyond rank ${fmt(rank)} in ${year}. ${summary}.</p>
    <div class="table-scroll"><table class="result-table">
      <thead><tr><th>Institute</th><th>Course</th><th>Quota</th>${rounds.map(r => `<th class="num">${r}<br><span class="dim">closing</span></th>`).join("")}</tr></thead>
      <tbody>${body}</tbody>
    </table></div>
    ${rows.length > predictorShown ? `<button type="button" class="chip more-btn" id="p-more">Show ${Math.min(100, rows.length - predictorShown)} more</button>` : ""}
    <p class="note">"—" means no one in your eligible categories was allotted that seat in that round.
    That usually means it was already filled, or wasn't offered in that category. Closing ranks move year to year with
    seat matrices and candidate counts, so compare a few years before relying on one.</p>`;
  const more = document.getElementById("p-more");
  if (more) more.addEventListener("click", () => {
    predictorShown += 100;
    renderPredictorResults(rows, rank, year, rounds, considered, true);
  });
}

/* ---------- Cutoff Explorer ---------- */
fillSelect("x-state", STATES.map(s => [s, s]), "All states");
fillSelect("x-program", PROGRAMS.map(p => [p, p]), "All programs");
fillSelect("x-specialty", SPECIALTIES.map(s => [s, s]), "All specialties");
fillSelect("x-quota", CUTOFFS.quotas.map((q, i) => [i, q]), "All quotas");
fillSelect("x-category", CUTOFFS.categories.map((c, i) => [i, c]), "All categories");
fillSelect("x-year", YEARS.map(y => [y, y]), "All years");
fillSelect("x-round", ROUND_ORDER.map(r => [r, r]), "All rounds");

let explorerRows = [], explorerShown = 100;
document.getElementById("explorer-form").addEventListener("submit", e => {
  e.preventDefault();
  const v = id => document.getElementById(id).value;
  const text = v("x-text").trim().toLowerCase();
  const instOk = CUTOFFS.institutes.map(([name, city, state]) =>
    (!v("x-state") || state === v("x-state")) &&
    (!text || `${name} ${city || ""} ${state || ""}`.toLowerCase().includes(text)));
  explorerRows = CUTOFFS.rows.filter(r => {
    const src = SOURCES[r[R.SRC]];
    return instOk[r[R.INST]]
      && courseMatches(r[R.COURSE], v("x-program"), v("x-specialty"))
      && (v("x-quota") === "" || r[R.QUOTA] === Number(v("x-quota")))
      && (v("x-category") === "" || r[R.CAT] === Number(v("x-category")))
      && (v("x-pwd") === "" || r[R.PWD] === Number(v("x-pwd")))
      && (!v("x-year") || src.year === Number(v("x-year")))
      && (!v("x-round") || src.round === v("x-round"));
  }).sort((a, b) => a[R.CLOSE] - b[R.CLOSE]);
  explorerShown = 100;
  renderExplorer();
});

function renderExplorer() {
  const el = document.getElementById("explorer-results");
  if (!explorerRows.length) {
    el.innerHTML = `<div class="empty-state">No rows match these filters.</div>`;
    return;
  }
  const body = explorerRows.slice(0, explorerShown).map(r => {
    const src = SOURCES[r[R.SRC]];
    return `<tr>
      <td>${src.year}<br><a class="dim" href="${esc(src.url)}" target="_blank" rel="noopener">${esc(src.round)}</a></td>
      <td>${instLabel(r[R.INST])}</td>
      <td>${esc(CUTOFFS.courses[r[R.COURSE]][0])}</td>
      <td>${esc(CUTOFFS.quotas[r[R.QUOTA]])}</td>
      <td>${esc(CUTOFFS.categories[r[R.CAT]])}${r[R.PWD] ? " <span class=\"pill\">PwD</span>" : ""}</td>
      <td class="num">${fmt(r[R.OPEN])}</td>
      <td class="num">${fmt(r[R.CLOSE])}</td>
      <td class="num">${r[R.SEATS]}</td>
    </tr>`;
  }).join("");
  el.innerHTML = `
    <p class="result-summary"><strong>${explorerRows.length.toLocaleString("en-IN")}</strong> rows, sorted by closing rank.
      <button type="button" class="chip" id="x-csv">⬇️ Download as CSV</button></p>
    <div class="table-scroll"><table class="result-table">
      <thead><tr><th>Year / Round</th><th>Institute</th><th>Course</th><th>Quota</th><th>Seat category</th>
        <th class="num">Opening</th><th class="num">Closing</th><th class="num">Allotted</th></tr></thead>
      <tbody>${body}</tbody>
    </table></div>
    ${explorerRows.length > explorerShown ? `<button type="button" class="chip more-btn" id="x-more">Show ${Math.min(100, explorerRows.length - explorerShown)} more</button>` : ""}`;
  const more = document.getElementById("x-more");
  if (more) more.addEventListener("click", () => { explorerShown += 100; renderExplorer(); });
  document.getElementById("x-csv").addEventListener("click", downloadExplorerCsv);
}

function downloadExplorerCsv() {
  const q = s => `"${String(s ?? "").replace(/"/g, '""')}"`;
  const lines = [["year", "round", "institute", "city", "state", "course", "program", "specialty", "quota", "seat_category", "pwd", "opening_rank", "closing_rank", "allotted", "source_pdf"].join(",")];
  for (const r of explorerRows) {
    const src = SOURCES[r[R.SRC]], [name, city, state] = CUTOFFS.institutes[r[R.INST]], c = CUTOFFS.courses[r[R.COURSE]];
    lines.push([src.year, q(src.round), q(name), q(city), q(state), q(c[0]), q(c[1]), q(c[2]), q(CUTOFFS.quotas[r[R.QUOTA]]),
      CUTOFFS.categories[r[R.CAT]], r[R.PWD], r[R.OPEN], r[R.CLOSE], r[R.SEATS], q(src.url)].join(","));
  }
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv" }));
  a.download = "neet-pg-cutoffs.csv";
  a.click();
  URL.revokeObjectURL(a.href);
}

/* ---------- Reservation Calculator ---------- */
document.getElementById("calc-form").addEventListener("submit", e => {
  e.preventDefault();
  const category = document.getElementById("c-category").value;
  const income = Number(document.getElementById("c-income").value) || 0;
  const pwd = document.getElementById("c-pwd").value === "yes";
  const inService = document.getElementById("c-inservice").value === "yes";

  const AIQ_RESERVATION = { "UR": 0, "EWS": 10, "OBC-NCL": 27, "SC": 15, "ST": 7.5 };
  const lines = [];

  lines.push(`Under <strong>AIQ</strong>, ${category === "UR" ? "UR/General candidates compete in the open, unreserved pool." : `${category} candidates are eligible for a reservation of approximately <strong>${AIQ_RESERVATION[category]}%</strong> of AIQ seats.`}`);

  if (pwd) {
    lines.push(`As a <strong>PwD</strong> candidate (≥40% benchmark disability), you're additionally eligible for the horizontal PwD reservation (commonly ~5% of seats), applied within your category.`);
  }

  if (category === "EWS") {
    if (income > 800000) {
      lines.push(`<span class="warn-line">⚠️ Your stated income (₹${income.toLocaleString()}) is above the commonly cited EWS threshold (₹8,00,000/year). Double-check the current official EWS criteria — you may not be eligible this cycle.</span>`);
    } else {
      lines.push(`Your stated income is within the commonly cited EWS threshold (₹8,00,000/year) — but the certificate must also satisfy asset/land-holding conditions and be issued for the current year.`);
    }
  }

  if (inService) {
    lines.push(`In-Service reservation is a <strong>State Quota</strong> category for doctors already employed in that state's government health department — eligibility (years of service, rural posting, etc.) is set independently by each state.`);
  }

  lines.push(`<span class="warn-line">State Quota reservation percentages and rules vary by state and are not modeled here — check your specific state's counseling bulletin.</span>`);

  document.getElementById("calc-results").innerHTML = `
    <div class="calc-summary">
      <h4>Your Reservation Snapshot</h4>
      <ul>${lines.map(l => `<li>${l}</li>`).join("")}</ul>
    </div>
  `;
});

/* ---------- Chatbot ---------- */
function scoreFaq(input, faq) {
  const words = input.toLowerCase().split(/\W+/).filter(Boolean);
  let score = 0;
  faq.keywords.forEach(k => {
    if (input.toLowerCase().includes(k)) score += k.split(" ").length * 2;
  });
  words.forEach(w => {
    if (faq.q.includes(w) && w.length > 2) score += 1;
  });
  return score;
}

function answerQuestion(input) {
  let best = null, bestScore = 0;
  FAQS.forEach(faq => {
    const s = scoreFaq(input, faq);
    if (s > bestScore) { bestScore = s; best = faq; }
  });
  if (best && bestScore > 0) return best.a;
  return "I don't have that in my FAQ list yet. Try rephrasing, check the Guide tab, or ask your official counseling authority. Try one of the suggestions below for what I do know.";
}

function appendChatMsg(text, who) {
  const win = document.getElementById("chat-window");
  const div = document.createElement("div");
  div.className = `chat-msg ${who}`;
  div.textContent = text;
  win.appendChild(div);
  win.scrollTop = win.scrollHeight;
}

document.getElementById("chat-form").addEventListener("submit", e => {
  e.preventDefault();
  const input = document.getElementById("chat-input");
  const text = input.value.trim();
  if (!text) return;
  appendChatMsg(text, "user");
  appendChatMsg(answerQuestion(text), "bot");
  input.value = "";
});

function renderChatSuggestions() {
  const row = document.getElementById("chat-suggestions");
  const sample = FAQS.slice(0, 8);
  row.innerHTML = "";
  sample.forEach(faq => {
    const chip = document.createElement("button");
    chip.type = "button";
    chip.className = "chip";
    chip.textContent = faq.q;
    chip.addEventListener("click", () => {
      appendChatMsg(faq.q, "user");
      appendChatMsg(faq.a, "bot");
    });
    row.appendChild(chip);
  });
}
renderChatSuggestions();
